services:
  postgres:
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - express-ts-drizzle-base-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        PORT: ${PORT}
        DATABASE_URL: ${DATABASE_URL}
        JWT_SECRET: ${JWT_SECRET}
        JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
        JWT_COOKIE_EXPIRES_IN: ${JWT_COOKIE_EXPIRES_IN}
    container_name: express-ts-drizzle-base-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:secret@postgres:5432/postgres
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - express-ts-drizzle-base-network

volumes:
  postgres:

networks:
  express-ts-drizzle-base-network:
